main: io.github.baptistemht.mariocraft.MarioCraft
name: MarioCraft
author: BaptisteMHT
version: 0.1
depend: [ProtocolLib]
api-version: 1.16
commands:
  start:
    description: Start game.
    usage: /start