main: io.github.baptistemht.mariocraft.MarioCraft
name: MarioCraft
author: BaptisteMHT
version: 0.1
depend: [ProtocolLib]
api-version: 1.13
commands:
  collision:
    description: Enable/Disable collisions.
    usage: /collision